### ISSUE TITLE
CPU host not valid device model name from a cloned template

### ISSUE THREAD

**Issue by Thimoty44** [jiangcuo/Proxmox-Port#52]
Hello,
Since I updated proxmox to version 8.1.3+pve1 to my raspbery pi 5 after cloning debian template that I ceated on my own. I can't start the cloned VM but my older VM dosen't have problem to start. I got the following error : 
kvm: -device host-x86_64-cpu,id=cpu2,socket-id=1,core-id=0,thread-id=0: 'host-x86_64-cpu' is not a valid device model name
TASK ERROR: start failed: QEMU exited with code 1

I tried selecting other things than host for CPU but nothing change.
I currently got the following kernel : Linux 6.1.0-rpi8-rpi-2712 (2024-01-25)
8 GB RAM 

Have a nice day.

**Comment by Thimoty44** [comment]
Ok I just find out if I let 1 socket on CPU it start but if I put more than 1 socket or core it don't start and I got the folowing error : kvm: -device host-x86_64-cpu,id=cpu2,socket-id=1,core-id=0,thread-id=0: 'host-x86_64-cpu' is not a valid device model name

**Comment by jiangcuo** [comment]
Can you update  more information?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**ENV (please complete the following information):**
 - OS: [e.g. debian11]
 - ARCH: [e.g. arm64,]
 - Version [ do `pveversion -v`]
- vmconfig [do `qm config {vmid}` and `qm showcmd {vmid} --pretty`]
**Additional context**
Add any other context about the problem here.

**Comment by jiangcuo** [comment]
There was no update, so the issue was closed
